<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>Work with User Stories, Sprints, Epics and Projects.</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Copado Developer</label>
    <tabs>copado__Pipeline_Manager</tabs>
    <tabs>copado__Project__c</tabs>
    <tabs>copado__User_Story__c</tabs>
    <tabs>copado__Work_Manager</tabs>
    <tabs>copado__Sprint__c</tabs>
    <tabs>copado__Epic__c</tabs>
    <tabs>copado__Theme__c</tabs>
    <tabs>copado__Test_Script__c</tabs>
    <tabs>copado__Test_Run__c</tabs>
    <tabs>copado__Release__c</tabs>
    <tabs>copado__Deployment_Flow__c</tabs>
    <tabs>copado__Promotion__c</tabs>
    <tabs>copado__Environment__c</tabs>
    <tabs>copado__Result__c</tabs>
    <tabs>copado__Scheduled_Job__c</tabs>
    <tabs>copado__External_CI_Setting__c</tabs>
    <tabs>copado__External_CI_Job__c</tabs>
    <tabs>copado__Team__c</tabs>
    <tabs>copado__User_Story_Metadata__c</tabs>
    <tabs>copado__Kanban_Board__c</tabs>
    <tabs>copado__Copado_DX_Panel</tabs>
    <tabs>copado__Burndown_Item__c</tabs>
    <tabs>copado__Application__c</tabs>
    <tabs>copado__Application_Feature__c</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>MetadataLoader</tabs>
    <tabs>PMC_SS_SalesArea__c</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
</CustomApplication>
