<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default_CSR</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>DEMO - CONSOLE</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.FAQ</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.FAQ</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.Procedure</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.Procedure</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TechnicalBulletinNotice</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TechnicalBulletinNotice</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TrainingDocument</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TrainingDocument</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TransitionDocument</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_Knowledge_Article_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Knowledge__kav</pageOrSobjectType>
        <recordType>Knowledge__kav.PMC_SS_TransitionDocument</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <setupExperience>service</setupExperience>
    <tabs>standard-Case</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>DEMO_CONSOLE_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>PMC_CPQ_Cadence__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_AccountSalesAreaRelationship__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_ActualPayment__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_IncentiveEarned__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SAP_Condition_Contract__c</tab>
        </mappings>
        <mappings>
            <tab>SBQQ__Subscription__c</tab>
        </mappings>
        <mappings>
            <tab>Test_V__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
