<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page1</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Use this application to sell.</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Sales</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_New_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.PMC_SS_Customer</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.PMC_SS_Customer</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>System Admin Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Sales Leadership</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Sales Insights Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Service User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Service Leadership</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>System Admin Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Sales Leadership</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Sales Insights Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Service User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Service Leadership</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Order_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Order</pageOrSobjectType>
        <recordType>Order.PMC_CPQ_Domestic</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_New_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.Ship_to_Customer_Legacy</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_New_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.Ship_to_Customer_Legacy</recordType>
        <type>Flexipage</type>
        <profile>Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_New_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.Ship_to_Customer_Legacy</recordType>
        <type>Flexipage</type>
        <profile>Service User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_SS_New_CustomerAccountLightningRecordPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.Ship_to_Customer_Legacy</recordType>
        <type>Flexipage</type>
        <profile>Master Data</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Campaign</tabs>
    <tabs>standard-Task</tabs>
    <tabs>standard-ContentNote</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-Feed</tabs>
    <tabs>standard-File</tabs>
    <tabs>standard-OtherUserProfile</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-Product2</tabs>
    <tabs>MobileLanding</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>MetadataLoader</tabs>
    <tabs>PMC_SS_SalesArea__c</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <tabs>PMC_Shipment_Data__c</tabs>
    <tabs>PMC_AccountSalesArea__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Sales_UtilityBar</utilityBar>
</CustomApplication>
