<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Optimizer</label>
    <navType>Console</navType>
    <tabs>standard-OrgMetric</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>PMC_CPQ_Cadence__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_AccountSalesAreaRelationship__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_ActualPayment__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_IncentiveEarned__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SAP_Condition_Contract__c</tab>
        </mappings>
        <mappings>
            <tab>SBQQ__Subscription__c</tab>
        </mappings>
        <mappings>
            <tab>Test_V__c</tab>
        </mappings>
        <mappings>
            <tab>standard-OrgMetric</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
