<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Product_Record_Page1</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Product2</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Commerce</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>PMC_DH_Commerce_Lightning_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>standard-WebStore</tabs>
    <tabs>standard-ProductWorkspace</tabs>
    <tabs>standard-PromotionsWorkspace</tabs>
    <tabs>standard-PricingWorkspace</tabs>
    <tabs>standard-CustomerWorkspace</tabs>
    <tabs>standard-ProductCatalog</tabs>
    <tabs>standard-PriceAdjustmentSchedule</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-CommerceEntitlementPolicy</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Order</tabs>
    <tabs>standard-OrderSummary</tabs>
    <tabs>standard-CommerceSetup</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>MetadataLoader</tabs>
    <tabs>PMC_SS_SalesArea__c</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_DH_EntitlementRules__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_DH_CommerceEntitlementSalesArea__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>standard-BusinessObjectivesRecommendations</tabs>
    <tabs>Test_V__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>MetadataLoader</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_Cadence__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_ProductLocation__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_ProductSalesArea__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_RawMaterial__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_DH_CommerceEntitlementSalesArea__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_DH_EntitlementRules__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_ErrorLog__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_AccountSalesAreaRelationship__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_ActualPayment__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_IncentiveEarned__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SAP_Condition_Contract__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SalesArea__c</tab>
        </mappings>
        <mappings>
            <tab>SBQQ__Subscription__c</tab>
        </mappings>
        <mappings>
            <tab>Test_V__c</tab>
        </mappings>
        <mappings>
            <tab>sbaa__Approval__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-BusinessObjectivesRecommendations</tab>
        </mappings>
        <mappings>
            <tab>standard-CommerceEntitlementPolicy</tab>
        </mappings>
        <mappings>
            <tab>standard-CommerceSetup</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-CustomerWorkspace</tab>
        </mappings>
        <mappings>
            <tab>standard-Order</tab>
        </mappings>
        <mappings>
            <tab>standard-OrderSummary</tab>
        </mappings>
        <mappings>
            <tab>standard-PriceAdjustmentSchedule</tab>
        </mappings>
        <mappings>
            <tab>standard-PricingWorkspace</tab>
        </mappings>
        <mappings>
            <tab>standard-ProductCatalog</tab>
        </mappings>
        <mappings>
            <tab>standard-ProductWorkspace</tab>
        </mappings>
        <mappings>
            <tab>standard-PromotionsWorkspace</tab>
        </mappings>
        <mappings>
            <tab>standard-WebStore</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
