<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Manufacturing</label>
    <navType>Standard</navType>
    <tabs>standard-home</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-AdvAcctForecastSetUse</tabs>
    <tabs>standard-SalesAgreement</tabs>
    <tabs>standard-AdvAcctForecastSetPartner</tabs>
    <tabs>standard-RebateProgram</tabs>
    <tabs>standard-RebateProgramMember</tabs>
    <tabs>standard-ProgramRebateType</tabs>
    <tabs>standard-Product2</tabs>
    <tabs>standard-Order</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Task</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-CollaborationGroup</tabs>
    <tabs>standard-TransactionJournal</tabs>
    <tabs>standard-RebateMemberAggregateItem</tabs>
    <tabs>standard-RebateClaim</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>MetadataLoader</tabs>
    <tabs>PMC_SS_SalesArea__c</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <tabs>Exspace__c</tabs>
    <tabs>Account_and_Product__c</tabs>
    <uiType>Lightning</uiType>
</CustomApplication>
