<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Business Rules Engine</label>
    <navType>Console</navType>
    <tabs>standard-DecisionTable</tabs>
    <tabs>standard-ExpressionSetTemplate</tabs>
    <tabs>standard-ExpressionSet</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>MetadataLoader</tabs>
    <tabs>PMC_SS_SalesArea__c</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>MetadataLoader</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_Cadence__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_ProductLocation__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_ProductSalesArea__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_CPQ_RawMaterial__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_ErrorLog__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_AccountSalesAreaRelationship__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_ActualPayment__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_IncentiveEarned__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SAP_Condition_Contract__c</tab>
        </mappings>
        <mappings>
            <tab>PMC_SS_SalesArea__c</tab>
        </mappings>
        <mappings>
            <tab>SBQQ__Subscription__c</tab>
        </mappings>
        <mappings>
            <tab>Test_V__c</tab>
        </mappings>
        <mappings>
            <tab>sbaa__Approval__c</tab>
        </mappings>
        <mappings>
            <tab>standard-DecisionTable</tab>
        </mappings>
        <mappings>
            <tab>standard-ExpressionSet</tab>
        </mappings>
        <mappings>
            <tab>standard-ExpressionSetTemplate</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
