<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-Chatter</tabs>
    <tabs>standard-File</tabs>
    <tabs>standard-Product2</tabs>
    <tabs>standard-Forecasting3</tabs>
    <tabs>standard-Quote</tabs>
    <tabs>MobileLanding</tabs>
    <tabs>PMC_CPQ_ProductLocation__c</tabs>
    <tabs>standard-WaveHome</tabs>
    <tabs>sbaa__Approval__c</tabs>
    <tabs>PMC_ErrorLog__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>PMC_SS_AllocationSummary__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <tabs>Exspace__c</tabs>
    <tabs>Account_and_Product__c</tabs>
    <tabs>PMC_Shipment_Data__c</tabs>
    <tabs>PMC_AccountSalesArea__c</tabs>
</CustomApplication>
