<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Case_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Case</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>PartnerVisits</label>
    <navType>Standard</navType>
    <tabs>standard-home</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Visit</tabs>
    <tabs>standard-ActionPlan</tabs>
    <tabs>standard-ActionPlanTemplate</tabs>
    <tabs>standard-GenericVisitTaskContext</tabs>
    <tabs>standard-GenericVisitTask</tabs>
    <tabs>standard-GnrcVstTaskContextRelation</tabs>
    <tabs>standard-AssessmentIndicatorDefinition</tabs>
    <tabs>standard-GnrcVstKeyPerformanceInd</tabs>
    <tabs>PMC_CPQ_ProductSalesArea__c</tabs>
    <tabs>PMC_CPQ_RawMaterial__c</tabs>
    <tabs>PMC_CPQ_Cadence__c</tabs>
    <tabs>SBQQ__Subscription__c</tabs>
    <tabs>PMC_SS_ActualPayment__c</tabs>
    <tabs>PMC_SS_IncentiveEarned__c</tabs>
    <tabs>PMC_SS_SAP_Condition_Contract__c</tabs>
    <tabs>PMC_SS_AccountSalesAreaRelationship__c</tabs>
    <tabs>Test_V__c</tabs>
    <uiType>Lightning</uiType>
</CustomApplication>
