public with sharing class BusinessSVCController {
    /*
    @AuraEnabled
    public static String getObjName(Id recordIdVal) {
        
        return recordIdVal.getSObjectType().getDescribe().getName();
    }
    
    @AuraEnabled
    public static String getFCval(Id recordIdVal) {
        
        return [SELECT PMC_SS_FieldCombination__c from PMC_SS_BusinessVolumeSelectionCriteria__c where id =:recordIdVal].PMC_SS_FieldCombination__c;
    }
    */
}