/**
 * @description       : Demo Class for Copado
 * @author            : siddharth.pradhan@mosaicco.com | Digital Hub
 * @group             : Mosaic Direct
 * @last modified on  : 07-24-2023
 * @last modified by  : siddharth.pradhan@mosaicco.com | Digital Hub
**/
public with sharing class GDA_Demo {

  
    /**
    * @description 
    * @author siddharth.pradhan@mosaicco.com | Digital Hub | 07-24-2023 
    * @return String 
    **/
    
    public static String mySampleMethod() {
        return 'Hello World';

    }
}