/**
* @description : Wrapper class for PMC_DH_UserInfoController
* @author      : Humera Rahath
* @userStory   : GDASF-540 & GDASF-5516 
* @last modified on 05-16-2023
* @last modified by @mhumerarahath
**/
public class PMC_DH_RegisterUserWrapper{
    /**
     * @description strLanguage
     * @return Language
     */
    @auraenabled
    public String strLanguage{get;set;}
    /**
     * @description strFirstName
     * @return First Name
     */
    @auraenabled
    public String strFirstName{get;set;}
    /**
     * @description strLastName
     * @return Last Name
     */
    @auraenabled
    public String strLastName{get;set;}
    /**
     * @description strEmail
     * @return Email
     */
    @auraenabled
    public String strEmail{get;set;}
    /**
     * @description strCountryCode
     * @return Country Code
     */
    @auraenabled
    public String strCountryCode{get;set;}
    /**
     * @description strPhoneNumber
     * @return Phone Number
     */
    @auraenabled
    public String strPhoneNumber{get;set;}
    /**
     * @description strCountry
     * @return Country
     */
    @auraenabled
    public String strCountry{get;set;}
    /**
     * @description strState
     * @return State
     */
    @auraenabled
    public String strState{get;set;}
    /**
     * @description strCity
     * @return City
     */
    @auraenabled
    public String strCity{get;set;}
    /**
     * @description strMarketingEmailConsent
     * @return Marketing Email Consent
     */
    @auraenabled
    public String strMarketingEmailConsent{get;set;}
    /**
     * @description strAccountNumber
     * @return Account Number
     */
    @auraenabled
    public String strAccountNumber{get;set;}
    /**
     * @description strUserType
     * @return User Type
     */
    @auraenabled
    public String strUserType{get;set;}
}