/**
 * @description This test class will be used to cover all the methods of PMC_ContactTriggerHandler and PMC_ContactTriggerHelper.
 * @author Sayali Shinde
 */

@isTest(seeAllData = false)
public with sharing class PMC_ContactTriggerHandlerTest {
    
    /**
    * @description This Method will be used to setup the test data for the test class execution.
    */
    
    @testsetup
    private static void setup() {
        
        Profile objUserProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        if(objUserProfile != null) {
            
            List<User> lstUser = PMC_TestUtilityClass.createUser(2);
            
            for(User objUser : lstUser) {
                objUser.ProfileId = objUserProfile.Id;
                objUser.IsActive = TRUE;
            }
            
            insert lstUser;            
            
            PMC_TestUtilityClass.createContact(5, '');  
            
            PMC_TestUtilityClass.createContactWithPhone();
        }
    }
    
    /** 
    * @description This method will be used to test the scenario where Case status is updated to Escalated and from Escalated to other Status.
    */ 
    
    @isTest
    private static void testDuplicateContacts() {
        Test.startTest();
        
        try{
            
            User objUser = [SELECT Id, Name FROM User WITH SECURITY_ENFORCED LIMIT 1];
            List<Contact> lstContacts = [SELECT Id, Name, Phone, HomePhone, MobilePhone, OtherPhone FROM Contact WITH SECURITY_ENFORCED];
            
            if(objUser != null && lstContacts.size() > 0) {
                System.runAs(objUser) { 

                    lstContacts[0].Phone = '1212121212';
                    lstContacts[0].HomePhone = '1313131313';
                    lstContacts[0].MobilePhone = '1414141414';
                    lstContacts[0].OtherPhone = '1515151515';
                    update lstContacts[0];                      
                    
                    List<Contact> lstContactsToBeUpdated = new List<Contact>();
                    
                    lstContacts[1].HomePhone = '1313131313'; 
                    lstContactsToBeUpdated.add(lstContacts[1]);
                    
                    lstContacts[2].Phone = '1212121212';
                    lstContactsToBeUpdated.add(lstContacts[2]);

                    lstContacts[3].MobilePhone = '1414141414';
                    lstContactsToBeUpdated.add(lstContacts[3]);
                    
                    lstContacts[4].OtherPhone = '1515151515';
                    lstContactsToBeUpdated.add(lstContacts[4]);
                    
                    update lstContactsToBeUpdated;                    
                }
            }
        }
        catch(Exception objException){
            System.assertNotEquals('', objException.getMessage(), 'Expected error log object to be created');
        }
        
        Test.stopTest();
    }
    
    /** 
    * @description This method will be used to test the Bypass Trigger Logic.
    */ 
    
    @isTest
    private static void testBypassUpdateOperation() {

        PMC_ContactTriggerHandler.boolBypassTriggerLogic = true;
        
        Test.startTest();
         User objUser = [SELECT Id, Name FROM User WITH SECURITY_ENFORCED LIMIT 1];
       	Contact objContact = [SELECT Id, Name, Phone, HomePhone, MobilePhone, OtherPhone FROM Contact WITH SECURITY_ENFORCED LIMIT 1 ];
        
        if(objUser != null && objContact != null) {
            System.runAs(objUser) {
                
                PMC_TestUtilityClass.createContact(1, '');
                
                objContact.Email = 'test@testqa.comm';
                update objContact;
            }
        }
        Test.stopTest();

        System.assertEquals('test@testqa.comm', [SELECT Id, Email FROM Contact WHERE Id=: objContact.Id].Email, 'Validating Contact EMail.');
    }
}