<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>PMC_SS_AutoGeneratedOpportunityEmailAlert</fullName>
        <description>Auto-Generated Opportunity Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>noreply.testmosaiccs@mosaicco.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/PMC_SS_AutoGeneratedOpportunityTemplate</template>
    </alerts>
    <alerts>
        <fullName>PMC_SS_NotifyOpportunityRetailerEmailAlert</fullName>
        <description>PMC SS Notify Opportunity Retailer Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>noreply.testmosaiccs@mosaicco.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>PMC_emails/PMC_SS_NotifyOpportunityRetailerForFollowUp</template>
    </alerts>
    <alerts>
        <fullName>PMC_SS_OpportunityApproachingCloseDate5DaysBeforeCloseEmailAlert</fullName>
        <description>Opportunity Approaching Close Date 5 Days Before Close Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>noreply.testmosaiccs@mosaicco.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/PMC_SS_OpportunityApproachingCloseDate5DaysBeforeCloseTemplate</template>
    </alerts>
    <alerts>
        <fullName>PMC_SS_OpportunityInactivityEmailAlert</fullName>
        <description>PMC SS Opportunity Inactivity Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>noreply.testmosaiccs@mosaicco.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>PMC_emails/PMC_SS_OpportunityInactivityNotificationTemplate</template>
    </alerts>
</Workflow>
